# Generated by Django 5.2.7 on 2025-11-01 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('efectivo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cartera_creditos_cp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cartera_creditos_lp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_activo_corriente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_activo_no_corriente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_activo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pasivo_corriente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pasivo_no_corriente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_pasivo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_patrimonio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='EstadoResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_servicios', models.DecimalField(decimal_places=2, max_digits=15)),
                ('resultado_bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utilidad_antes_impuestos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utilidad_neta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'ano')},
            },
        ),
    ]
